import { build } from "esbuild";
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { checkPlugin, MAX_FILE_BYTES } from "./check-plugin.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const plugin = join(root, "plugin");
const outdir = join(plugin, "runtime");
const modulePath = (specifier) => fileURLToPath(import.meta.resolve(specifier));

// Explicit vendor entry points give esbuild readable module boundaries instead
// of a single ~617 KB bundle. Keep minification off and enforce the size budget
// after dependency updates; ordinary splitting alone leaves an oversized chunk.
const result = await build({
  absWorkingDir: root,
  entryPoints: {
    index: "mcp-server/src/index.ts",
    client: "mcp-server/src/client.ts",
    gate: "mcp-server/src/gate.ts",
    "vendor/zod-schemas": fileURLToPath(new URL("./schemas.js", import.meta.resolve("zod/v4/core"))),
    "vendor/mcp-types": modulePath("@modelcontextprotocol/sdk/types.js"),
    "vendor/mcp-protocol": modulePath("@modelcontextprotocol/sdk/shared/protocol.js"),
    "vendor/ajv-core": modulePath("ajv/dist/core.js"),
  },
  bundle: true,
  splitting: true,
  minify: false,
  platform: "node",
  format: "esm",
  target: "node20",
  outdir,
  outExtension: { ".js": ".mjs" },
  chunkNames: "chunks/[name]-[hash]",
  legalComments: "inline",
  metafile: true,
  write: false,
});

for (const file of result.outputFiles) {
  if (file.contents.length >= MAX_FILE_BYTES) {
    throw new Error(`${relative(root, file.path)} is ${file.contents.length} bytes; add a vendor entry point to split it below ${MAX_FILE_BYTES}.`);
  }
}

// Preserve the licenses of every bundled dependency, including transitive ones.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.includes("node_modules/")) continue;
  let directory = dirname(resolve(root, input));
  while (directory !== root && directory !== dirname(directory)) {
    const path = join(directory, "package.json");
    if (existsSync(path)) {
      const pkg = JSON.parse(readFileSync(path, "utf8"));
      if (pkg.name && pkg.version) {
        packages.set(pkg.name, { directory, pkg });
        break;
      }
    }
    directory = dirname(directory);
  }
}
const notices = ["# Bundled third-party licenses\n", "Generated by `npm run build`. These dependencies are included as readable JavaScript.\n"];
for (const [name, { directory, pkg }] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
  const license = ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENSE-MIT", "license", "license.md"].find((name) => existsSync(join(directory, name)));
  if (!license) throw new Error(`Missing license for bundled dependency ${name}`);
  notices.push(`## ${name} ${pkg.version} (${pkg.license})\n\n${readFileSync(join(directory, license), "utf8").trim()}\n`);
}

rmSync(outdir, { recursive: true, force: true });
for (const file of result.outputFiles) {
  mkdirSync(dirname(file.path), { recursive: true });
  writeFileSync(file.path, file.contents);
}
copyFileSync(join(root, "favicon.png"), join(plugin, "favicon.png"));
copyFileSync(join(root, "LICENSE"), join(plugin, "LICENSE"));
writeFileSync(join(plugin, "THIRD_PARTY_NOTICES.md"), notices.join("\n"));
const files = checkPlugin(plugin);
console.log(`Built plugin: ${files.length} files; largest JavaScript module ${Math.max(...result.outputFiles.map((file) => file.contents.length))} bytes (limit < ${MAX_FILE_BYTES}).`);
